service: serverless-chat
frameworkVersion: '2'

provider:
  name: aws
  stage: dev
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: eu-central-1
  websocketApiName: serverless-chat-api
  websocketApiRouteSelectionExpression: $request.body.action
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - "execute-api:ManageConnections"
          Resource:
            - "arn:aws:execute-api:*:*:**/@connections/*"
        - Effect: Allow
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:UpdateItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:BatchGetItem"
            - "dynamodb:BatchWriteItem"
            - "dynamodb:Scan"
            - "dynamodb:Query"
          Resource:
            - "arn:aws:dynamodb:eu-central-1:*:*"

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  connectionManager:
    handler: handler.connection_manager
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
  defaultMessage:
    handler: handler.default_message
    events:
      - websocket:
          route: $default
  getRecentMessages:
    handler: handler.get_recent_messages
    events:
      - websocket:
          route: getRecentMessages
  sendMessage:
    handler: handler.send_message
    events:
      - websocket:
          route: sendMessage
  ping:
    handler: handler.ping
    events:
      - http:
          path: ping
          method: get
